### ISSUE TITLE
fix: cannot authenticate to Managed Grafana instance

### ISSUE THREAD

**Issue by hknutsen** [equinor/terraform-azurerm-grafana#7]
1. Prompted to login using Microsoft account.
2. I login using my Equinor account.
3. Redirected to white page with title "Working...".
4. Never get past the white page.

Would like to resolve this before we push Managed Grafana on projects.

**Comment by hknutsen** [comment]
I am able to login using Edge, but not Firefox.

In Chrome I get "Your connection is not private", however I can click "Proceed to <grafana_url>" to bypass the warning.

Should document this as a known potential issue.

Could also open a ticket with Microsoft.

**Comment by hknutsen** [comment]
Applied `examples/complete` and created a support ticket with Microsoft.

**Comment by sebastianlolv** [comment]
Recieved answer from Microsoft Support. They were able to reproduce the issue and the issue has been escalated to the Product Group at Microsoft.

**Comment by hknutsen** [comment]
The issue in Chrome was related to an invalid certificate configuration by Microsoft. This has been resolved.

The issue in Firefox still persists. Waiting for further response from Microsoft.

**Comment by hknutsen** [comment]
@sebastianlolv Microsoft support closed the ticket even though we expressed that we still had issues with Firefox. Can you take this further?

**Comment by sebastianlolv** [comment]
Email to Microsoft Support about the Firefox "Working..." issue has been sent. Awaiting response.

**Comment by sebastianlolv** [comment]
Still no answer back after a week after reminder mail was sent, I suspect they wont be notified since they closed the case. Maybe we need to open a seperate issue for this issue just to get an answer back. Problem still persists.

**Comment by hknutsen** [comment]
@sebastianlolv Opening a new ticket seems like the way to go.

**Comment by hknutsen** [comment]
@sebastianlolv Could you follow this up?

**Comment by sebastianlolv** [comment]
New response. There is a limitation when using Firefox. Firefox browser only supported on Windows devices when it comes to conditional access (https://learn.microsoft.com/en-us/azure/active-directory/conditional-access/concept-conditional-access-conditions#supported-browsers).

**Comment by sebastianlolv** [comment]
The case handler suggests to try using Firefox, but activate Windows SSO login in Firefox. The problem there is that Windows SSO login is already activated through organization and it still doesn't work. As the final suggestion is that we continue use the working browsers as a workaround for the time being.

**Comment by hknutsen** [comment]
@sebastianlolv Could you document this limitation in the README?

**Comment by sebastianlolv** [comment]
Case handler has taken the issue with Windows SSO login already activated and still doesn't work internally. Handler will come back next week with further details.

**Comment by sebastianlolv** [comment]
Case will be closed with no fix, but problem is passed internally at Microsoft.
